<?php

class CGIComActions{
	const ELEMENT_SYNTHESIS_SETUP = 	"ELEMENT SYNTHESIS SETUP";
	const ELEMENT_SYNTHESIS_UPDATE = 	"ELEMENT SYNTHESIS UPDATE";
	const GET_RATE_LIST = 				"GET RATE LIST";
	const GET_RATE_INFO = 				"GET RATE INFO";
	const MODIFY_RATE_LIBRARY = 		"MODIFY RATE LIBRARY";
	const MODIFY_RATES = 				"MODIFY RATES";
	const SYNTHESIZE_ELEMENTS = 		"SYNTHESIZE ELEMENTS";
}

?>