<?php

class SimWorkflowMode{
	const SINGLE_STANDARD = 			"SINGLE_STANDARD";
	const SINGLE_STANDARD_SENS = 		"SINGLE_STANDARD_SENS";
	const SINGLE_CUSTOM = 				"SINGLE_CUSTOM";
	const SINGLE_CUSTOM_SENS = 			"SINGLE_CUSTOM_SENS";
	const DIR_STANDARD = 				"DIR_STANDARD";
	const DIR_CUSTOM_DOUBLE_LOOPING = 	"DIR_CUSTOM_DOUBLE_LOOPING";
	const DIR_CUSTOM_SINGLE_LOOPING = 	"DIR_CUSTOM_SINGLE_LOOPING";
}

?>