!Moved from the original directory and added the CVS info
!
!   $Author: bucknerk $
!   $Id: reacinfo.f90,v 1.1.1.1 2008/04/22 13:36:33 bucknerk Exp $
!   $Log: reacinfo.f90,v $
!   Revision 1.1.1.1  2008/04/22 13:36:33  bucknerk
!   all in one place
!
!   Revision 1.2  2007/07/17 19:12:40  bucknerk
!   Don't need this any more.
!
!   
PROGRAM reacinfo
  USE IFLPORT
  USE cina_core
  IMPLICIT NONE
  TYPE(cina_common)               :: pcom

  ! Print HEADER to tell webserver what response cina is returning
  WRITE(*,'(A/)') 'Content-Type: text/plain'

  CALL chk_cgi_env

  ! Get HEADER, ID, ACTION, USER, PW, etc.
  pcom = get_cina_common()

  ! Set action to reacinfo
  ! This allows us to tell which errors in ErrorLog were generated by this program
  pcom%ACTION = 'reacinfo'

  ! Check for correct HEADER version
  SELECT CASE (pcom%HEADER)
  CASE ('1.8')
     ! Do nothing
  CASE DEFAULT
     CALL report_error('The server software has been upgraded '//      &
          'to the point that this program must be updated.'//LF//      &
          'The header sent by your software is '//TRIM(pcom%HEADER)//LF// &
          'Please visit http://astrodata/upgrade'//                    &
          ' or email cina@astrodata','Severe Authencation',pcom,1)
  END SELECT

  ! Execute the check reaction action
  CALL chk_reaction(pcom)
END PROGRAM reacinfo
